apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  namespace: cs3219
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - name: catalog
        image: qinxutan/catalog-service:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080