apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: cs3219
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order
        image: qinxutan/order-service:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: CATALOG_SERVICE_URL
          value: "http://catalog-service.cs3219.svc.cluster.local:8080"